# Use Node base image
FROM node:20

WORKDIR /app

# Install dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy frontend code
COPY frontend/ .

# Expose dev server port (or remove if building for prod)
EXPOSE 5173

CMD ["npm", "run", "dev"]
